name: myfinance_improved
description: MyFinance - Toss-style financial management app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.0
  riverpod_annotation: ^2.3.0
  
  # Navigation
  go_router: ^13.0.0
  
  # Data & API
  supabase_flutter: ^2.3.0
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.0.0
  
  # UI Components
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  flutter_slidable: ^3.0.1

  flutter_svg: ^2.0.10
  image_picker: ^1.0.7
  
  # Utilities
  freezed_annotation: ^2.4.0
  json_annotation: ^4.8.0
  intl: ^0.19.0
  uuid: ^4.5.1
  
  # Icons
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  
  # QR Code Scanner
  # mobile_scanner: ^3.5.0  # Temporarily disabled due to Firebase conflict
  
  # Location Services
  geolocator: ^11.0.0
  
  # Firebase & Push Notifications
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  firebase_analytics: ^11.2.0
  flutter_local_notifications: ^17.2.1
  
  # Permission Handling
  permission_handler: ^11.3.1
  
  # Deep Linking
  app_links: ^6.1.1
  
  # Debugging
  logger: ^2.0.2
  path_provider: ^2.1.2
  
  # Timezone for notifications
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  freezed: ^2.4.0
  json_serializable: ^6.7.0
  riverpod_generator: ^2.3.0
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  # Fonts
  #   
  #   - family: JetBrains Mono
  #     fonts:
  #       - asset: assets/fonts/JetBrainsMono-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/JetBrainsMono-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/JetBrainsMono-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/JetBrainsMono-Bold.ttf
  #         weight: 700
  #   
  #   - family: Noto Sans JP
  #     fonts:
  #       - asset: assets/fonts/NotoSansJP-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/NotoSansJP-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/NotoSansJP-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/NotoSansJP-Bold.ttf
  #         weight: 700

# App Icon Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_storebase_icon.svg.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo_storebase_icon.svg.png"

# Splash Screen Configuration  
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logo_storebase_stacked.svg.png"
  color_dark: "#000000"
  image_dark: "assets/images/logo_storebase_horizontal_white.svg.png"
  android_12:
    image: "assets/images/logo_storebase_icon.svg.png"
    color: "#FFFFFF"
  ios: true
  android: true