name: myfinance_improved
description: MyFinance - Toss-style financial management app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.0
  riverpod_annotation: ^2.3.0
  
  # Navigation
  go_router: ^13.0.0
  
  # Data & API
  supabase_flutter: ^2.3.0
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.0.0
  
  # UI Components
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  flutter_slidable: ^3.0.1
  
  # Utilities
  freezed_annotation: ^2.4.0
  json_annotation: ^4.8.0
  intl: ^0.19.0
  
  # Icons
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  
  # QR Code Scanner
  mobile_scanner: ^5.1.1
  
  # Location Services
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  freezed: ^2.4.0
  json_serializable: ^6.7.0
  riverpod_generator: ^2.3.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  # Fonts
  #   
  #   - family: JetBrains Mono
  #     fonts:
  #       - asset: assets/fonts/JetBrainsMono-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/JetBrainsMono-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/JetBrainsMono-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/JetBrainsMono-Bold.ttf
  #         weight: 700
  #   
  #   - family: Noto Sans JP
  #     fonts:
  #       - asset: assets/fonts/NotoSansJP-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/NotoSansJP-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/NotoSansJP-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/NotoSansJP-Bold.ttf
  #         weight: 700