// lib/features/report_control/presentation/pages/templates/cash_location/domain/entities/example_cash_location_data.dart

import 'cash_location_report.dart';

/// Example data for Cash Location Report
///
/// Organized for store-grouped view:
/// - Only stores with issues
/// - Multiple locations per store
/// - Last entry info for investigation
///
/// Based on real data from session be7d099f-62b9-445b-a1cc-0cd0534cbafc
class ExampleCashLocationData {
  static CashLocationReport get sampleReport => CashLocationReport(
        reportDate: '2025-12-04',
        currencySymbol: '₫',
        currencyCode: 'VND',
        heroStats: const CashLocationHeroStats(
          totalLocations: 20,
          balancedCount: 11,
          issuesCount: 9,
          shortageCount: 8,
          surplusCount: 1,
          totalBookAmount: 1094715047,
          totalActualAmount: 433263487,
          netDifference: -661451560,
          overallStatus: 'major_issues',
          totalBookFormatted: '1,094,715,047 ₫',
          totalActualFormatted: '433,263,487 ₫',
          netDifferenceFormatted: '-661,451,560 ₫',
        ),
        locationsByStore: const [],
        recentEntries: const [],
        // Issues grouped by store in the data
        // Store: Cameraon Nha Trang (3 issues)
        // Store: Headsup Nha Trang (2 issues)
        // Store: Cameraon Chua Boc (1 issue)
        // Store: Headsup Hanoi (2 issues)
        // Store: Cameraon Nhat Chieu (1 issue)
        issues: const [
          // ===== STORE: Cameraon Nha Trang (3 issues) =====
          CashLocationIssue(
            locationId: 'loc-13',
            locationName: 'Vault NT CameraOn',
            locationType: 'vault',
            storeId: 'store-nt-cam',
            storeName: 'Cameraon Nha Trang',
            bookAmount: 447704000,
            actualAmount: 0,
            difference: -447704000,
            bookFormatted: '447,704,000 ₫',
            actualFormatted: '0 ₫',
            differenceFormatted: '-447,704,000 ₫',
            issueType: 'shortage',
            severity: 'high',
            lastEntry: LastEntryInfo(
              entryId: 'entry-nt-vault-1',
              employeeId: 'emp-nha-xink',
              employeeName: 'Nha Xink',
              entryDate: '2025-12-04',
              entryTime: '16:45',
              amount: -15000000,
              formattedAmount: '-15,000,000 ₫',
              description: 'Vault out transaction',
              entryType: 'vault_out',
            ),
          ),
          CashLocationIssue(
            locationId: 'loc-12',
            locationName: 'TPBank NT Camera On (Trang)',
            locationType: 'bank',
            storeId: 'store-nt-cam',
            storeName: 'Cameraon Nha Trang',
            bookAmount: 19170527,
            actualAmount: 10584839,
            difference: -8585688,
            bookFormatted: '19,170,527 ₫',
            actualFormatted: '10,584,839 ₫',
            differenceFormatted: '-8,585,688 ₫',
            issueType: 'shortage',
            severity: 'medium',
            lastEntry: LastEntryInfo(
              entryId: 'entry-nt-cam-bank-1',
              employeeId: 'emp-trang',
              employeeName: 'Trang',
              entryDate: '2025-12-04',
              entryTime: '11:15',
              amount: -3200000,
              formattedAmount: '-3,200,000 ₫',
              description: 'Utility payment',
              entryType: 'bank_transfer',
            ),
          ),
          CashLocationIssue(
            locationId: 'loc-11',
            locationName: 'Cashier NT CameraOn',
            locationType: 'cash',
            storeId: 'store-nt-cam',
            storeName: 'Cameraon Nha Trang',
            bookAmount: 8252000,
            actualAmount: 8352000,
            difference: 100000,
            bookFormatted: '8,252,000 ₫',
            actualFormatted: '8,352,000 ₫',
            differenceFormatted: '+100,000 ₫',
            issueType: 'surplus',
            severity: 'low',
            lastEntry: LastEntryInfo(
              entryId: 'entry-nt-cam-cash-1',
              employeeId: 'emp-nha-xink',
              employeeName: 'Nha Xink',
              entryDate: '2025-12-04',
              entryTime: '18:00',
              amount: -600000,
              formattedAmount: '-600,000 ₫',
              description: 'Cash ending',
              entryType: 'cash_ending',
            ),
          ),

          // ===== STORE: Headsup Nha Trang (2 issues) =====
          CashLocationIssue(
            locationId: 'loc-20',
            locationName: 'Vault NT HU',
            locationType: 'vault',
            storeId: 'store-hu-nt',
            storeName: 'Headsup Nha Trang',
            bookAmount: 82430000,
            actualAmount: 0,
            difference: -82430000,
            bookFormatted: '82,430,000 ₫',
            actualFormatted: '0 ₫',
            differenceFormatted: '-82,430,000 ₫',
            issueType: 'shortage',
            severity: 'high',
            lastEntry: LastEntryInfo(
              entryId: 'entry-nt-hu-vault-1',
              employeeId: 'emp-linh-nt',
              employeeName: 'Linh NT',
              entryDate: '2025-12-04',
              entryTime: '15:30',
              amount: -8000000,
              formattedAmount: '-8,000,000 ₫',
              description: 'Vault out for daily operation',
              entryType: 'vault_out',
            ),
          ),
          CashLocationIssue(
            locationId: 'loc-19',
            locationName: 'TPBank NT HU (Trang)',
            locationType: 'bank',
            storeId: 'store-hu-nt',
            storeName: 'Headsup Nha Trang',
            bookAmount: 11171000,
            actualAmount: 6100152,
            difference: -5070848,
            bookFormatted: '11,171,000 ₫',
            actualFormatted: '6,100,152 ₫',
            differenceFormatted: '-5,070,848 ₫',
            issueType: 'shortage',
            severity: 'medium',
            lastEntry: LastEntryInfo(
              entryId: 'entry-hu-nt-bank-1',
              employeeId: 'emp-trang-nt',
              employeeName: 'Trang NT',
              entryDate: '2025-12-04',
              entryTime: '10:00',
              amount: -1500000,
              formattedAmount: '-1,500,000 ₫',
              description: 'Petty cash replenishment',
              entryType: 'bank_transfer',
            ),
          ),

          // ===== STORE: Headsup Hanoi (2 issues) =====
          CashLocationIssue(
            locationId: 'loc-15',
            locationName: 'TP Bank',
            locationType: 'bank',
            storeId: 'store-hu-hn',
            storeName: 'Headsup Hanoi',
            bookAmount: 50862834,
            actualAmount: 10728983,
            difference: -40133851,
            bookFormatted: '50,862,834 ₫',
            actualFormatted: '10,728,983 ₫',
            differenceFormatted: '-40,133,851 ₫',
            issueType: 'shortage',
            severity: 'high',
            lastEntry: LastEntryInfo(
              entryId: 'entry-hu-hn-bank-1',
              employeeId: 'emp-le-an',
              employeeName: 'Le An',
              entryDate: '2025-12-04',
              entryTime: '13:45',
              amount: -5000000,
              formattedAmount: '-5,000,000 ₫',
              description: 'Supplier payment',
              entryType: 'bank_transfer',
            ),
          ),
          CashLocationIssue(
            locationId: 'loc-16',
            locationName: 'Vault HU HN',
            locationType: 'vault',
            storeId: 'store-hu-hn',
            storeName: 'Headsup Hanoi',
            bookAmount: 2890000,
            actualAmount: 0,
            difference: -2890000,
            bookFormatted: '2,890,000 ₫',
            actualFormatted: '0 ₫',
            differenceFormatted: '-2,890,000 ₫',
            issueType: 'shortage',
            severity: 'low',
            lastEntry: LastEntryInfo(
              entryId: 'entry-hu-hn-vault-1',
              employeeId: 'emp-jin2',
              employeeName: 'Jin2 Lee',
              entryDate: '2025-12-04',
              entryTime: '09:30',
              amount: -24610000,
              formattedAmount: '-24,610,000 ₫',
              description: 'Multi-currency vault recount',
              entryType: 'vault_recount',
            ),
          ),

          // ===== STORE: Cameraon Chua Boc (1 issue) =====
          CashLocationIssue(
            locationId: 'loc-3',
            locationName: 'TP bank CB',
            locationType: 'bank',
            storeId: 'store-cb',
            storeName: 'Cameraon Chua Boc',
            bookAmount: 109643737,
            actualAmount: 64377737,
            difference: -45266000,
            bookFormatted: '109,643,737 ₫',
            actualFormatted: '64,377,737 ₫',
            differenceFormatted: '-45,266,000 ₫',
            issueType: 'shortage',
            severity: 'high',
            lastEntry: LastEntryInfo(
              entryId: 'entry-cb-bank-1',
              employeeId: 'emp-kha-anh',
              employeeName: 'Kha Anh',
              entryDate: '2025-12-04',
              entryTime: '14:20',
              amount: -2500000,
              formattedAmount: '-2,500,000 ₫',
              description: 'Bank transfer out',
              entryType: 'bank_transfer',
            ),
          ),

          // ===== STORE: Cameraon Nhat Chieu (1 issue) =====
          CashLocationIssue(
            locationId: 'loc-8',
            locationName: 'TP bank - (Nhat Chieu)',
            locationType: 'bank',
            storeId: 'store-nc',
            storeName: 'Cameraon Nhat Chieu',
            bookAmount: 71146582,
            actualAmount: 41675409,
            difference: -29471173,
            bookFormatted: '71,146,582 ₫',
            actualFormatted: '41,675,409 ₫',
            differenceFormatted: '-29,471,173 ₫',
            issueType: 'shortage',
            severity: 'medium',
            lastEntry: LastEntryInfo(
              entryId: 'entry-nc-bank-1',
              employeeId: 'emp-nhung-phan',
              employeeName: 'Nhung Phan',
              entryDate: '2025-12-04',
              entryTime: '12:30',
              amount: -1800000,
              formattedAmount: '-1,800,000 ₫',
              description: 'Daily expense transfer',
              entryType: 'bank_transfer',
            ),
          ),
        ],
        aiInsights: const CashLocationInsights(
          summary:
              '9 locations across 5 stores require attention with a total discrepancy of -661M ₫. Cameraon Nha Trang has the most critical issues with vault showing complete depletion.',
          recommendations: [
            'Prioritize Cameraon Nha Trang vault (-447M ₫) - contact Nha Xink',
            'Review all vault locations showing zero actual balance',
            'Verify bank statement reconciliation for TP Bank accounts',
            'Check employee access logs for high-severity locations',
          ],
        ),
      );
}
