import 'package:equatable/equatable.dart';

/// Company entity representing a created company
/// Returned after successful company creation
class Company extends Equatable {
  const Company({
    required this.id,
    required this.name,
    required this.code,
    required this.companyTypeId,
    required this.baseCurrencyId,
  });

  /// Unique identifier (company_id from database)
  final String id;

  /// Company name as entered by user
  final String name;

  /// Auto-generated company code for invitations (e.g., "COMP12345")
  /// Generated by database trigger
  final String code;

  /// Reference to company type (FK to company_types)
  final String companyTypeId;

  /// Reference to base currency (FK to currency_types)
  final String baseCurrencyId;

  @override
  List<Object?> get props => [id, name, code, companyTypeId, baseCurrencyId];

  @override
  String toString() => 'Company(id: $id, name: $name, code: $code)';
}
