import 'package:equatable/equatable.dart';

/// Store entity representing a created store
/// Returned after successful store creation
class Store extends Equatable {
  const Store({
    required this.id,
    required this.name,
    required this.code,
    required this.companyId,
    this.address,
    this.phone,
    this.huddleTime,
    this.paymentTime,
    this.allowedDistance,
  });

  /// Unique identifier (store_id from database)
  final String id;

  /// Store name as entered by user
  final String name;

  /// Auto-generated store code for invitations (e.g., "STORE56789")
  /// Generated by database trigger
  final String code;

  /// Reference to parent company (FK to companies)
  final String companyId;

  /// Optional store address (5-500 characters)
  final String? address;

  /// Optional store phone number (regex validated)
  final String? phone;

  /// Minutes for team meetings/huddle (1-1440, default: 15)
  final int? huddleTime;

  /// Minutes for payment processing (1-1440, default: 30)
  final int? paymentTime;

  /// Maximum distance in meters for check-in (1-10000, default: 100)
  final int? allowedDistance;

  @override
  List<Object?> get props => [
        id,
        name,
        code,
        companyId,
        address,
        phone,
        huddleTime,
        paymentTime,
        allowedDistance,
      ];

  @override
  String toString() => 'Store(id: $id, name: $name, code: $code, companyId: $companyId)';
}
