// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIzu9bfy0w0V3ufK7jDDYNzDcEEkTn5S0',
    appId: '1:204633647743:web:29fc37c93c33d969a12d4a',
    messagingSenderId: '204633647743',
    projectId: 'notification-f1653',
    authDomain: 'notification-f1653.firebaseapp.com',
    storageBucket: 'notification-f1653.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIzu9bfy0w0V3ufK7jDDYNzDcEEkTn5S0',
    appId: '1:204633647743:android:29fc37c93c33d969a12d4a',
    messagingSenderId: '204633647743',
    projectId: 'notification-f1653',
    storageBucket: 'notification-f1653.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIzu9bfy0w0V3ufK7jDDYNzDcEEkTn5S0',
    appId: '1:204633647743:ios:deb0f3c99fa71951a12d4a',
    messagingSenderId: '204633647743',
    projectId: 'notification-f1653',
    storageBucket: 'notification-f1653.firebasestorage.app',
    iosBundleId: 'com.storebase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIzu9bfy0w0V3ufK7jDDYNzDcEEkTn5S0',
    appId: '1:204633647743:ios:deb0f3c99fa71951a12d4a',
    messagingSenderId: '204633647743',
    projectId: 'notification-f1653',
    storageBucket: 'notification-f1653.firebasestorage.app',
    iosBundleId: 'com.storebase.app',
  );
}